name: Documentation

on:
  push:
    branches: [ development, master ]
    paths-ignore:
      - 'src/pretix/locale/**'
      - 'src/pretix/static/**'
      - 'src/tests/**'
  pull_request:
    branches: [ development, master ]
    paths-ignore:
      - 'src/pretix/locale/**'
      - 'src/pretix/static/**'
      - 'src/tests/**'

jobs:
  spelling:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.14
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install system packages
        run: sudo apt update && sudo apt install hunspell aspell-en
      - name: Install Dependencies
        run: pip3 install -Ur doc/requirements.txt
      - name: Spellcheck docs
        run: make spelling
        working-directory: ./doc
      - name: Check if the output file is empty or not
        run: '[ ! -s _build/spelling/output.txt ]'
        working-directory: ./doc
